### ISSUE TITLE
Livereload doesn't work

### ISSUE THREAD

**Issue by jonadeline** [NewbranLTD/gulp-server-io#11]
Hi,

I'm experimenting an issue with the livereload. Changes to my app files are detected but the browser doesn't reload. 
In the console I got the following messages : 
```
[12:25:26] { msg:
   [ 'TypeError: Cannot read property \'length\' of undefined',
     'at http://localhost:8000/debugger-io/debugger-client.js:58:17' ],
  from: 'error',
  color: 'debug',
  browser: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36',
  location: 'http://localhost:8000/' }
[12:25:33] [Watcher] File changed
[12:25:33] change /Users/jonathan/Google Drive/Documents/Jonathan/Sites/wedding/www/index.html
Sending message to 0 connection(s): reload
``` 

Here is my gulpfile : 

```
const { gulp } = require('gulp-server-io/gulp');
const gulpServerIo = require('gulp-server-io');

gulp.task('serve', () => {
  return gulp.src('./www').pipe(gulpServerIo());
});
```

**Comment by joelchu** [comment]
Which version are you using? And what platform you are running from? 

You can run the "ncu -a" to see if your dependecies are all up to date. 

Cheers

**Comment by jonadeline** [comment]
Hi, 

Thx for your quick answer.
I'm using the latest version of gulp-server-io and I'm on Mac OS X 10.13.
All the dependencies are up to date.

**Comment by joelchu** [comment]
OK Just release v1.0.1, please try it and see if the problem still there; as far as I know it's fixed, but it's always great someone else test it :)

**Comment by jonadeline** [comment]
That works perfectly. Thank you very much for the quick fixing ;)

**Comment by joelchu** [comment]
Cool, I am glad it's fixed. If you like it, please do star the project :)
