### ISSUE TITLE
livereload css problem

### ISSUE THREAD

**Issue by stanrust** [NewbranLTD/gulp-server-io#19]
when i change css i want livereload can inject css into page without reload whole page. like gulp-connect did.

**Comment by joelchu** [comment]
That's nothing to do with the webserver. It's the gulp file does it for you. 
This module doesn't aim to solve this particular problem. You might want to check out my other generator which setup the development gulpfile.

**Comment by joelchu** [comment]
BTW - if you don't want to setup a full blow gulpfile (which actually you need to one way or the other) but you can use the middleware array to hook into the index.html stream. Then inject whatever file you want into it.
